# Site settings
---
layout: post
title: Abitha Natarajan CV
theme: Tactile
---

  <h1>{{ page.title }}</h1>
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/abithasanjeevi/
 -title: Get the pdf version of my resume here
   url: https://www.visualcv.com/abithasanjeevi/pdf/

<p class="head">{{ page.url}}</p>