
# Site settings
title: Abitha Natarajan
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      theme: jekyll-theme-cayman