# Site settings
title: Abitha Natarajan CV
name: Abitha Natarajan
theme: Minimal
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: LinkedIn
   url: https://www.linkedin.com/in/abithasanjeevi/
 -title: Get the pdf version of my resume here
   url: https://www.visualcv.com/abithasanjeevi/pdf/

#Any buzzword skills you want to include
skills:
Experienced Performance Consultant/ QA.
Specialized in:
Neoload
JMeter
HP Load runner (Performance Testing of Web based applications) Expertise in - Web/HTTP
protocol, Web Services protocol
Various monitoring tools - HP Site scope, Ganglia, New Relic and Cloud era Manager
HP Quality Center
Test automation enthusiast. Experienced Agile methodologist (Scrum Fundamentals Certified )
New Relic Certified Performance 

#Work experience is required
roles:
 - title: Performance Consultant
   start: September 2018
   end: Ongoing
   employer: AccessHQ
   description: Performance Consultant, working for multiple clients on consultation mode, responsible for analyzingand comparing NFRs with business expectations, test the load capability of various applications. <br/> On various engagements with different clients- News Corp Australia, Stateplus (First State Super), Department of Agriculture and Fisheries - QLD. 
   
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham
#This section is optional (as is the image link below)

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>JVM</strong>: I am experienced in a variety of Java API’s and frameworks. I have recently worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others.  In my current role Groovy is the primary language used - and I am familiar with many of the languages features and quirks (including writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>).
A